# Generated by Django 5.1.11 on 2025-07-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="adresse_facturation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="adresse_livraison",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="date_livraison",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="livraison_statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("en_cours", "En cours"),
                    ("livre", "Livré"),
                    ("annule", "Annulé"),
                ],
                default="en_attente",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="mode_paiement",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="status_paiement",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("paid", "Payé"),
                    ("failed", "Échoué"),
                    ("refunded", "Remboursé"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="telephone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
