# Generated by Django 5.1.11 on 2025-07-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_back",
            field=models.ImageField(
                blank=True, null=True, upload_to="books/covers/back/"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="cover_front",
            field=models.ImageField(
                blank=True, null=True, upload_to="books/covers/front/"
            ),
        ),
    ]
