# Generated by Django 5.1.11 on 2025-07-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_cover_back_book_cover_front"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
