# Generated by Django 5.1.11 on 2025-07-04 17:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
        ("books", "0005_book_price_book_price_currency"),
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="auteurs",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="authors.author"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="code_barres",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="book",
            name="collection",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="date_ajout",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="dimensions",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="editeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="publishers.publisher",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="format",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="book",
            name="illustrateur",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="niveau_scolaire",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="book",
            name="poids",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="public_cible",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
