# Generated by Django 5.1.11 on 2025-07-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Avis validé"),
        ),
    ]
