# Generated by Django 5.2.4 on 2025-07-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("contact", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
